<?php

namespace Database\Seeders;

use App\Models\Menu;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $menus = [
            ////////////RICE TOPPINGS//////////
            [
                'name' => 'Lechon Kawali',
                'description' => 'w/rice - 1p',
                'category' => "Rice Toppings",
                'price' => 110,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Lechon Paksiw',
                'description' => 'w/rice - 1p',
                'category' => "Rice Toppings",
                'price' => 100,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Leg Quarter',
                'description' => 'w/rice - 1p',
                'category' => "Rice Toppings",
                'price' => 140,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Pork Adobo',
                'description' => 'w/rice - 1p',
                'category' => "Rice Toppings",
                'price' => 100,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Sweet & Sour Pork',
                'description' => 'w/rice - 1p',
                'category' => "Rice Toppings",
                'price' => 100,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Sze Chuan Beef Brisket',
                'description' => 'w/rice - 1p',
                'category' => "Rice Toppings",
                'price' => 120,
                'max_level' => 50,
                'warning_level' => 20,
            ],

            //////////GUISADO///////////
            [
                'name' => 'Ampalaya Con Beef',
                'description' => '2-3p',
                'category' => "Guisado",
                'price' => 180,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Ampalaya Con Carne',
                'description' => '2-3p',
                'category' => "Guisado",
                'price' => 180,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Braised Tofu',
                'description' => '2-3p',
                'category' => "Guisado",
                'price' => 130,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Chicken Curry',
                'description' => '2-3p',
                'category' => "Guisado",
                'price' => 260,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Chicken Chopsuey',
                'description' => '2-3p',
                'category' => "Guisado",
                'price' => 180,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Chopsuey Guisado',
                'description' => '2-3p',
                'category' => "Guisado",
                'price' => 180,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Sweet & Sour Fish Fillet',
                'description' => '2-3p',
                'category' => "Guisado",
                'price' => 200,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Sweet & Sour MeatBalls',
                'description' => '2-3p',
                'category' => "Guisado",
                'price' => 180,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Sweet & Sour Pork',
                'description' => '2-3p',
                'category' => "Guisado",
                'price' => 180,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Sze Chuan Beef Brisket',
                'description' => '2-3p',
                'category' => "Guisado",
                'price' => 220,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Tokwa Baboy Con Sarsa',
                'description' => '2-3p',
                'category' => "Guisado",
                'price' => 180,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Tokwa Con Fish Fillet',
                'description' => '2-3p',
                'category' => "Guisado",
                'price' => 220,
                'max_level' => 50,
                'warning_level' => 20,
            ],

            ///////////PANCIT SPECIAL/////////////
            [
                'name' => 'Bihon',
                'description' => '2-3p',
                'category' => "Pancit Special",
                'price' => 200,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Canton',
                'description' => '2-3p',
                'category' => "Pancit Special",
                'price' => 220,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Canton w/ Bihon',
                'description' => '2-3p',
                'category' => "Pancit Special",
                'price' => 220,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Lomi',
                'description' => '2-3p',
                'category' => "Pancit Special",
                'price' => 200,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Miki (Chami)',
                'description' => '2-3p',
                'category' => "Pancit Special",
                'price' => 200,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Miki (Bihon)',
                'description' => '2-3p',
                'category' => "Pancit Special",
                'price' => 200,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Pancit Chopsuey',
                'description' => '2-3p',
                'category' => "Pancit Special",
                'price' => 220,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Sotanghon',
                'description' => '2-3p',
                'category' => "Pancit Special",
                'price' => 220,
                'max_level' => 50,
                'warning_level' => 20,
            ],

            //////PANCIT SA BILAO (for take-out only)////////////

            //BIHON
            [
                'name' => 'Bihon #12',
                'description' => '6-7p',
                'category' => "PSB",
                'price' => 380,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Bihon #14',
                'description' => '10-12p',
                'category' => "PSB",
                'price' => 550,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Bihon #16',
                'description' => '15-18p',
                'category' => "PSB",
                'price' => 900,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Bihon #18',
                'description' => '22-25p',
                'category' => "PSB",
                'price' => 1300,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            //MIKI BIHON
            [
                'name' => 'Miki Bihon #12',
                'description' => '6-7p',
                'category' => "PSB",
                'price' => 380,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Miki Bihon #14',
                'description' => '10-12p',
                'category' => "PSB",
                'price' => 550,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Miki Bihon #16',
                'description' => '15-18p',
                'category' => "PSB",
                'price' => 900,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Miki Bihon #18',
                'description' => '22-25p',
                'category' => "PSB",
                'price' => 1300,
                'max_level' => 50,
                'warning_level' => 20,
            ],

            //CANTON
            [
                'name' => 'Canton #12',
                'description' => '6-7p',
                'category' => "PSB",
                'price' => 480,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Canton #14',
                'description' => '10-12p',
                'category' => "PSB",
                'price' => 650,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Canton #16',
                'description' => '15-18p',
                'category' => "PSB",
                'price' => 1000,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Canton #18',
                'description' => '22-25p',
                'category' => "PSB",
                'price' => 1500,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            //CANTON BIHON
            [
                'name' => 'Canton Bihon #12',
                'description' => '6-7p',
                'category' => "PSB",
                'price' => 480,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Canton Bihon #14',
                'description' => '10-12p',
                'category' => "PSB",
                'price' => 650,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Canton Bihon #16',
                'description' => '15-18p',
                'category' => "PSB",
                'price' => 1000,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Canton Bihon #18',
                'description' => '22-25p',
                'category' => "PSB",
                'price' => 1500,
                'max_level' => 50,
                'warning_level' => 20,
            ],

            ////////MAMI & SELFMADE SIOPAO////////
            [
                'name' => 'Beef Mami',
                'description' => '1p',
                'category' => "MSS",
                'price' => 80,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Chicken Mami',
                'description' => '1p',
                'category' => "MSS",
                'price' => 80,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Siopao Asado',
                'description' => '1p',
                'category' => "MSS",
                'price' => 55,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Mantou 4pcs',
                'description' => '4pcs',
                'category' => "MSS",
                'price' => 60,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Fried Mantou 4pcs',
                'description' => '4pcs',
                'category' => "MSS",
                'price' => 70,
                'max_level' => 50,
                'warning_level' => 20,
            ],

            ///////////CHICKEN///////////

            //FRIED
            [
                'name' => 'Fried Chicken L H',
                'description' => 'Large - Half',
                'category' => "Chicken",
                'price' => 220,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Fried Chicken L W',
                'description' => 'Large - Whole',
                'category' => "Chicken",
                'price' => 420,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Fried Chicken J H',
                'description' => 'Jumbo - Half',
                'category' => "Chicken",
                'price' => 240,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Fried Chicken J W',
                'description' => 'Jumbo - Whole',
                'category' => "Chicken",
                'price' => 460,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            //STEAM
            [
                'name' => 'Steam Chicken L H',
                'description' => 'Large - Half',
                'category' => "Chicken",
                'price' => 240,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Steam Chicken L W',
                'description' => 'Large - Whole',
                'category' => "Chicken",
                'price' => 440,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Steam Chicken J H',
                'description' => 'Jumbo - Half',
                'category' => "Chicken",
                'price' => 260,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Steam Chicken J W',
                'description' => 'Jumbo - Whole',
                'category' => "Chicken",
                'price' => 480,
                'max_level' => 50,
                'warning_level' => 20,
            ],

            //////////////FRIED////////////////

            [
                'name' => 'Calamares',
                'description' => '-',
                'category' => "Fried",
                'price' => 220,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Camaron',
                'description' => '-',
                'category' => "Fried",
                'price' => 220,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Chicharon Bulaklak',
                'description' => '-',
                'category' => "Fried",
                'price' => 200,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Chicken Wings',
                'description' => '-',
                'category' => "Fried",
                'price' => 160,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Crispy Pata',
                'description' => '-',
                'category' => "Fried",
                'price' => 720,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'French Fries',
                'description' => '-',
                'category' => "Fried",
                'price' => 100,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Breaded Tofu',
                'description' => '-',
                'category' => "Fried",
                'price' => 130,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Fried Tofu/Tokwa',
                'description' => '-',
                'category' => "Fried",
                'price' => 100,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Fried Tokwa Baboy',
                'description' => '-',
                'category' => "Fried",
                'price' => 180,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Kikiam',
                'description' => '-',
                'category' => "Fried",
                'price' => 120,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Lumpia Shanghai',
                'description' => '-',
                'category' => "Fried",
                'price' => 180,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Torta Con Carne',
                'description' => '-',
                'category' => "Fried",
                'price' => 180,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'TQQ Chicken',
                'description' => '-',
                'category' => "Fried",
                'price' => 200,
                'max_level' => 50,
                'warning_level' => 20,
            ],

            /////////////SOUP//////////////
            [
                'name' => 'Chicken Mushroom',
                'description' => '4-5p',
                'category' => "Soup",
                'price' => 150,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Hototay Soup',
                'description' => '4-5p',
                'category' => "Soup",
                'price' => 150,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Sotanghon Soup',
                'description' => '4-5p',
                'category' => "Soup",
                'price' => 150,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Sweet Corn w/ Egg',
                'description' => '4-5p',
                'category' => "Soup",
                'price' => 150,
                'max_level' => 50,
                'warning_level' => 20,
            ],

            /////////////ROAST & SIZZLING//////////////
            [
                'name' => 'Bangus',
                'description' => '-',
                'category' => "Roast & Sizzling",
                'price' => 180,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Chicken Mushrrom',
                'description' => '-',
                'category' => "Roast & Sizzling",
                'price' => 160,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Mixed Seafood',
                'description' => '-',
                'category' => "Roast & Sizzling",
                'price' => 200,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Pork Chop',
                'description' => '-',
                'category' => "Roast & Sizzling",
                'price' => 180,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Pusit',
                'description' => '-',
                'category' => "Roast & Sizzling",
                'price' => 180,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Sisig',
                'description' => '-',
                'category' => "Roast & Sizzling",
                'price' => 180,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Spicy Roast Beef',
                'description' => '-',
                'category' => "Roast & Sizzling",
                'price' => 240,
                'max_level' => 50,
                'warning_level' => 20,
            ],

            //////////DESSERT/////////////
            [
                'name' => 'Taho',
                'description' => '-',
                'category' => "Dessert",
                'price' => 20,
                'max_level' => 50,
                'warning_level' => 20,
            ],

            //////////BEVERAGES/////////////
            [
                'name' => 'Soya Milk',
                'description' => '-',
                'category' => "Beverages",
                'price' => 30,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Soya Milk 4pcs',
                'description' => '-',
                'category' => "Beverages",
                'price' => 100,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Plum Ice Tea',
                'description' => '-',
                'category' => "Beverages",
                'price' => 25,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Plum Ice Tea 5pcs',
                'description' => '-',
                'category' => "Beverages",
                'price' => 100,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Mineral Water 500ml',
                'description' => '-',
                'category' => "Beverages",
                'price' => 25,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Softdrinks',
                'description' => '-',
                'category' => "Beverages",
                'price' => 25,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Softdrinks 1.5L',
                'description' => '-',
                'category' => "Beverages",
                'price' => 120,
                'max_level' => 50,
                'warning_level' => 20,
            ],

            ///////SIDE DISHES//////////
            [
                'name' => 'Atchara',
                'description' => '-',
                'category' => "Side Dishes",
                'price' => 60,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Chili Sause',
                'description' => '-',
                'category' => "Side Dishes",
                'price' => 100,
                'max_level' => 50,
                'warning_level' => 20,
            ],

            ////////////EXTRA///////////////
            [
                'name' => 'Fried Rice',
                'description' => '1cup',
                'category' => "Extra",
                'price' => 60,
                'max_level' => 50,
                'warning_level' => 20,
            ],
            [
                'name' => 'Plain Rice',
                'description' => '1cup',
                'category' => "Extra",
                'price' => 25,
                'max_level' => 50,
                'warning_level' => 20,
            ],
        ];

        foreach ($menus as $key => $menu) {
            Menu::create($menu);
        }
    }
}
